language: java
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: ZvJAOCTM5nEkDqY/+voQ84blzZE6DyUlx39otrOPbIHsHnw7t0NKt2chl3zLkng0p6ETqneQKlgovmvmaqHvjEkbVp3yNudxdG/6MvTUI4xU9z5ToSTqDa86KPI/8JGnEnAHM+7C0aG4gzrhPZLrWGxAq6jN8ejoe0YbfWXe7piuzwoss9ygNc+3VVopRYJBcudhY27jQ0g2AxHiVvCFcMWAqdyo4JNfWMzKkRombBve0o06A1Fmr9lFN/z3LDV0bt7pPTE3WaoPkoNNn6beAug4DzO+7fXPhDD1a5hZ3lmGlMUJMSq5JkEgcFnpoziO7jwfE5ZyRfrJq0Ejq9QbtVzRQ4uUfuUumM6vVBf4wudpo3A8XLCkSN1S9WbMe2Pqw6Y9K6krzoBzU7wOtaaBApUWa7WdUVBeeYsqIAt2zcj53D97xV0KwWfB59twoqcKoio4nlFPU+ejn+nxK6bQj/1QeQoVXtMRV+QGWw/96PadZOl37lVyOy0RU4cWoIxw4N7lC6Bj7m3w5UdHF/ez4BKb8RbfWWt2JPsuGVymJ0XK2yCjWTqojW5zeWEGqMeJNAIFnSZzNWy6y6sgfSQIZlfU6YHsJov4CkAb4RlmjPLQ9RxnQeL31D1iyDGA60gh+Lr1MV2tJ2tDiNz4ClEZkArAyokK0Lk+GG6SKEBylgI=
  file: 
    - './releng/net.sdruskat.peppergrinder.product/target/products/pepper-grinder-0.1.2-linux.gtk.x86_64.zip'
    - './releng/net.sdruskat.peppergrinder.product/target/products/pepper-grinder-0.1.2-win32.win32.x86_64.zip'
    - './releng/net.sdruskat.peppergrinder.product/target/products/pepper-grinder-0.1.2-macosx.cocoa.x86_64.zip'
  on:
    repo: sdruskat/pepper-grinder
    branch: master
